### ISSUE TITLE
Could Integration with SponsorBlock be added?

### ISSUE THREAD

**Issue by PhlegethonAcheron** [yt-dlg/yt-dlg#1]
[ ] Bug report
 Feature request (request for a new functionality)
[ ] Question
[ ] Other
Feature request (request for a new functionality)
 I've verified and i assure that my requested feature is NOT in the TODO list
What operating system do you use ?
Win10, Arch
Integration with sponsorblock would allow undesirable portions of videos to be cut out of the download, such that sponsor or plug the merch segments could be omitted from the download, and for music videos, the "non-music" section could be omitted from the download.

I haven't worked with APIs before, so this might not be possible, but would be absolutely amazing to have. I'm pretty familiar with python, so I might be able to implement this myself, but don't know if it would be possible, or even wanted.

**Comment by oleksis** [comment]
@PhlegethonAcheron Check the last [Release 1.5.0](https://github.com/oleksis/youtube-dl-gui/releases/tag/v1.5.0); Add support for CLI Backends like yt-dlp which support [**Sponsorblock**](https://github.com/yt-dlp/yt-dlp#sponskrub-sponsorblock-options)

**Comment by oleksis** [comment]
@PhlegethonAcheron can check the last Release resolve the issue and the can close it?
