### ISSUE TITLE
Downloading YouTube doesn't work.

### ISSUE THREAD

**Issue by lunamoth** [yt-dlg/yt-dlg#11]
[v] **I think** my problem is **NOT** with **youtube-dl**
 [v] Bug report

### Bug report
2023-02-19 21:30:43,714-DEBUG-Worker_1-ERROR: [youtube] xqovGKdgAXY: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
2023-02-19 21:30:43,715-DEBUG-Worker_1-Child process exited with non-zero code: 1

#### What operating system do you use ?
Windows  10

#### What happens instead ?

- The yt-dlp command line command downloads fine.

- With yt-dlg, it suddenly fails to download.

- For reference, I put the following version of yt-dlp in the folder
https://github.com/yt-dlp/yt-dlp/releases/tag/2023.02.17

**Comment by oleksis** [comment]
Update to the latest version of `yt-dlp` CLI Backend version 2023.02.17 go to `Setting -> Update`. Try download the URL again.

![image](https://user-images.githubusercontent.com/44526468/219954128-a5f252b3-f711-4603-ae85-c4b45af9f1cd.png)

Logs:
![image](https://user-images.githubusercontent.com/44526468/219954276-b028b109-1bf1-48e4-b775-159a942ae3d1.png)

**Comment by lunamoth** [comment]
Thank you for your response. I deleted the yt-dlp that I manually put in the folder and updated it from yt-dlg and tried running it. It works fine.

I thought the auto-update was out of date (now that I checked, it's up to date). Now I'm going to use auto-update

**Comment by oleksis** [comment]
Please, if work as expected, feel free to close the issue. Thanks for the feedbacks!
