### ISSUE TITLE
File registration in Transifex is not correct

### ISSUE THREAD

**Issue by maboroshin** [yt-dlg/yt-dlg#13]
#### List of actions to perform to reproduce the problem:

  1. Access transifex and try to translate yt-dlg.
  2. There are at least 10 selectable resources. Non-English resources are registered.

#### What is the expected behaviour ?
Resources whose source text is in English can be selected.

#### What happens instead ?

Other languages can also be selected as source texts. For example, the original text is in Japanese, or Chinese .... These are not the translated language.

Probably only English language files should be registered on Transifex.

**Comment by oleksis** [comment]
The English resource is: https://www.transifex.com/yt-dlg/yt-dlg/youtube-dl-gui-locale-en-us-lc-messages-youtube-dl-gui-po--master/

The goal is get **100% translated** others languages

**Comment by maboroshin** [comment]
It fixed.
